spring:
  cloud:
    function:
      definition: processorBinding;consumerBinding
    stream:
      bindings:
        processorBinding-in-0:
          destination: processor-topic
        processorBinding-out-0:
          destination: consumer-topic
        consumerBinding-in-0:
          destination: consumer-topic
      kafka:
        binder:
          replicationFactor: 1
          brokers:
            - localhost:9092
